logging:
  version: 1
  disable_existing_loggers: true
  formatters:
      standard:
          format: "%(asctime)s [%(levelname)8s][%(name)s] %(message)s"
          datefmt: "%H:%M:%S"
      verbose:
          format: "runid-{run_id}|%(levelname)s|%(asctime)s|PID %(process)d|%(processName)s|%(name)s|%(pathname)s|%(funcName)s|%(lineno)d|%(message)s"
  handlers:
      console:
          class: logging.StreamHandler
          level: INFO
          formatter: standard
          stream: ext://sys.stdout

      # info_file_handler:
      #     class: logging.handlers.RotatingFileHandler
      #     level: INFO
      #     formatter: standard
      #     filename: info.log
      #     maxBytes: 1048576 # 1 MiB
      #     backupCount: 3
      #     encoding: utf8

      # error_file_handler:
      #     class: logging.handlers.RotatingFileHandler
      #     level: ERROR
      #     formatter: verbose
      #     filename: errors.log
      #     maxBytes: 1048576 # 1 MiB
      #     backupCount: 3
      #     encoding: utf8

      debug_file_handler:
          class: logging.handlers.RotatingFileHandler
          level: DEBUG
          formatter: verbose
          filename: debug.log
          maxBytes: 1048576 # 1 MiB
          backupCount: 3
          encoding: utf8

      # critical_file_handler:
      #     class: logging.handlers.RotatingFileHandler
      #     level: CRITICAL
      #     formatter: verbose
      #     filename: critical.log
      #     maxBytes: 1048576 # 1 MiB
      #     backupCount: 3
      #     encoding: utf8
      #
      # warn_file_handler:
      #     class: logging.handlers.RotatingFileHandler
      #     level: WARN
      #     formatter: verbose
      #     filename: warn.log
      #     maxBytes: 1048576 # 1 MiB
      #     backupCount: 3
      #     encoding: utf8

  root:
      level: DEBUG
      handlers: [console, debug_file_handler]
      propagate: yes

  # loggers:
  #     ch_demo_2021:
  #         level: INFO
  #         handlers: [console]
  #         propagate: no
  #     #
  #     ch_demo_2021.datasets._pdf:
  #         level: DEBUG
  #         handlers: [console, debug_file_handler]
  #         propagate: no

runtime_settings:
  image_prep:
    minimum_entropy: 2.0
    minimum_pixel_height: 16
    minimum_pixel_width: 16
    minimum_pixel_total: 64
